### ISSUE TITLE
Errors sometimes happen mid-upload and are not recoverable

### ISSUE THREAD

**Issue by ctengel** [ctengel/objectindex#49]
Two issues - 
1. Error happens during upload
   - maybe not actually a problem
2. No way to continue upload

### Details on the issue

Client side

```

...

  File "site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/http/client.py", line 998, in send
    self.sock.sendall(datablock)
ConnectionResetError: [Errno 104] Connection reset by peer

...

  File "scripts/yt.py", line 39, in upload
    flob = client.upload_metadata(filename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/obj_idx/client.py", line 138, in upload_metadata
    bucket.upload_file(filename, s3_url['key'])
  File "site-packages/boto3/s3/inject.py", line 233, in bucket_upload_file
    return self.meta.client.upload_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...

  File "site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/botocore/httpsession.py", line 504, in send
    raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "http://objstore:9000/bucket/key?uploadId=uploadId&partNumber=2".
```

Server side:
```
API: PutObjectPart(bucket=bucket, object=key)
DeploymentID: uuid
RequestID: anotherid
RemoteHost: client
Host: objstore:9000
UserAgent: Boto3/1.28.33 md/Botocore#1.31.33 ua/2.0 os/linux#6.4.6-200.fc38.x86_64 md/arch#x86_64 lang/python#3.11.4 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.31.33 Resource
Error: read tcp objstore:9000->client:456789: read: connection reset by peer (*net.OpError)
Aug 24 14:09:45 csenysbobj1 start.sh[16338]:        7: internal/logger/logger.go:258:logger.LogIf()
Aug 24 14:09:45 csenysbobj1 start.sh[16338]:        6: cmd/erasure-encode.go:96:cmd.(*Erasure).Encode()
Aug 24 14:09:45 csenysbobj1 start.sh[16338]:        5: cmd/erasure-multipart.go:697:cmd.erasureObjects.PutObjectPart()
Aug 24 14:09:45 csenysbobj1 start.sh[16338]:        4: cmd/erasure-sets.go:906:cmd.(*erasureSets).PutObjectPart()
Aug 24 14:09:45 csenysbobj1 start.sh[16338]:        3: cmd/erasure-server-pool.go:1496:cmd.(*erasureServerPools).PutObjectPart()
Aug 24 14:09:45 csenysbobj1 start.sh[16338]:        2: cmd/object-multipart-handlers.go:830:cmd.objectAPIHandlers.PutObjectPartHandler()
Aug 24 14:09:45 csenysbobj1 start.sh[16338]:        1: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()
```

### No continue

More to come on this but essentially
1. This is left as a file with complete=False and maybe a half uploaded partial
2. Is there a mechanism to complete partial?
3. Delete and start over?
4. if initiate as a new upload...
5. OI will say already exists
6. Since complete=False though will not know what to do

### The fix
More than likely need a way to 
1. cleanup partial upload, delete completely from S3
2. Either delete DB entries OR handle incomplete case, somehow mark no longer in progress.... deleted=True complete=False maybe?

**Comment by ctengel** [comment]
Attempted retry - 
```

...


  File "scripts/yt.py", line 39, in upload
    flob = client.upload_metadata(filename,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/obj_idx/client.py", line 123, in upload_metadata
    my_file = obj_idx.initiate_upload(url=url,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/obj_idx/clilib.py", line 117, in initiate_upload
    info = self.post('upload/', json=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/obj_idx/clilib.py", line 77, in post
    result.raise_for_status()
  File "site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://objidx:5000/upload/
```


Server:

```
ERROR in app: Exception on /upload/ [POST]
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
...
  File "site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "site-packages/obj_idx/api.py", line 118, in post
    assert my_obj.completed
AssertionError
... "POST /upload/ HTTP/1.1" 500 -
```

**Comment by ctengel** [comment]
Same error seen again... related to simultaneous uploads?

No log on server, just client. Maybe just a LAN issue...

**Comment by ctengel** [comment]
seems like simple connectivity.... two issues
- NUC still on WiFi
- LAN probably due for upgrade

**Comment by ctengel** [comment]
#2 is likely the main fix

secondary issue is code

**Comment by ctengel** [comment]
allegedly  Linux 6.4.7 fixes this - we are currently at 6.4.6 - see https://discussion.fedoraproject.org/t/rtl8111-8168-8411-realtek-ethernet-controller-not-working-r8169-related/86593/10

**Comment by ctengel** [comment]
Minio seems to clear multipart automatically after 24 hours

Correct way to deal then (once cleared from minio)
1. Set deleted=True (keep complete=False) - this will signify it's retriable
   - need to set PUT/PATCH /object/ to allow this
   - trigger manually via API for now?
2. Do POST /upload as usual
   - need to modify to allow new upload if deleted=True and complete=False
 3. do PUT/PATCH object with complete=True deleted=False
    - need to ensure API allows it
    - client to include deleted=False in PATCH?

**Comment by ctengel** [comment]
Negative, POST /upload will reset both to 0 so it will complete as usual.  No need to change client at all really.

**Comment by ctengel** [comment]
This has been successfully tested so let's just document the PUT /object/ deleted=True and then we are good.
